basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Expense Monster BE API.
  termsOfService: https://example.com/terms/
  title: Expense Monster BE
  version: "1.0"
paths: {}
swagger: "2.0"
